/**
 * Serialize a value for embedding inside `<script type="application/ld+json">`.
 *
 * `JSON.stringify` alone is NOT safe here. It escapes nothing that matters to an HTML parser,
 * so a string value containing `</script>` closes the element early and everything after it is
 * parsed as markup. Blog frontmatter reaches JSON-LD (a post `title` becomes `headline`), so in
 * a template where content is authored — or generated by an agent from a brief — that input is
 * not trusted.
 *
 * Escaping `<` as `<` neutralizes `</script>` and `<!--` at once. The result is still valid
 * JSON and still parses to exactly the same object: `<` is the JSON escape for `<`.
 */
export function serializeJsonLd(value: unknown): string {
  return JSON.stringify(value).replace(/</g, '\\u003c');
}
